#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config focus_follows_pointer true

bspc config border_width         0
bspc config window_gap          30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#bspc rule -a Zoom desktop='^8'

# Patches for java applications like jetbarins IDE
wmname LG3D

# Set the wallpaper
feh --bg-fill ~/Pictures/background/bg1.jpg

# Autolaunch polybar script
sh ~/.config/polybar/launch.sh

# Autolaunch picom
picom &

killall mopidy
mopidy &

# Autolaunch applets (system tray)
nm-applet &
blueman-applet &
fcitx &
#conky &
